# Generated by Django 5.2.6 on 2025-11-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('texto', models.TextField()),
                ('etiqueta', models.CharField(choices=[('positivo', 'positivo'), ('negativo', 'negativo')], max_length=10)),
            ],
        ),
    ]
