# Generated by Django 5.2.8 on 2025-11-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dia_semana', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('pacientes', models.IntegerField()),
                ('es_feriado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Demanda de Pacientes',
                'verbose_name_plural': 'Demanda de Pacientes',
                'ordering': ['-fecha'],
            },
        ),
    ]
